server:
  port: 8082
  servlet:
    context-path: /springbootconsumer

spring:
  application:
    name: spring-boot-consumer

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/springcloudeureka/eureka/

spring-boot-provider:
  ribbon:
    NFLoadBalancerRuleClassName: cn.wbnull.springbootconsumer.config.loadbalancer.GlobalRule
